controller_names:
  - rebel_6dof_controller

rebel_6dof_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - igus_joint1
    - igus_joint2
    - igus_joint3
    - igus_joint4
    - igus_joint5
    - igus_joint6