/**:
  ros__parameters:
    robot_description_kinematics:
      rebel_6dof:
        kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
        solve_type: Distance # Speed, Manipulation1, Manipulation2, Distance
        kinematics_solver_timeout: 0.05 # 0.005
        kinematics_solver_attempts: 10



  
#use this configs for standard kdl ik solver:
        # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        # kinematics_solver_search_resolution: 0.005
        # kinematics_solver_timeout: 0.005
        # kinematics_solver_attempts: 3